version: '3'

services:

  db:
    image: "mysql:5.7"
    hostname: db
    ports:
      - "3306:3306"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: dostavim

    networks:
      - db_net

  webapp:
    build: ./DostavimVse
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=90
    depends_on:
      - db
    ports:
      - "8080:8080"

    networks:
      - db_net

networks:
  db_net:
    
    
